export const mockBooths = [
  {
    id: '1',
    name: 'Google Vietnam',
    company: 'Google',
    sector: 'Technology',
    visitorCount: 127,
    status: 'active',
    representative: 'Nguyen Van A',
    position: '001',
  },
  {
    id: '2',
    name: 'Samsung Electronics',
    company: 'Samsung',
    sector: 'Electronics',
    visitorCount: 98,
    status: 'active',
    representative: 'Tran Thi B',
    position: '002',
  },
  {
    id: '3',
    name: 'FPT Software',
    company: 'FPT',
    sector: 'Software',
    visitorCount: 156,
    status: 'active',
    representative: 'Hoang Van C',
    position: '003',
  },
  {
    id: '4',
    name: 'Viettel Solutions',
    company: 'Viettel',
    sector: 'Telecommunications',
    visitorCount: 89,
    status: 'active',
    representative: 'Pham Thi D',
    position: '004',
  },
  {
    id: '5',
    name: 'Accenture Vietnam',
    company: 'Accenture',
    sector: 'Consulting',
    visitorCount: 112,
    status: 'active',
    representative: 'Le Van E',
    position: '005',
  },
  {
    id: '6',
    name: 'Saigon Software',
    company: 'Saigon Tech',
    sector: 'Software',
    visitorCount: 73,
    status: 'active',
    representative: 'Ngo Thi F',
    position: '006',
  },
]

export const mockVisitors = [
  {
    id: '1',
    name: 'Nguyen Anh Duc',
    major: 'Information Technology',
    year: 3,
    timestamp: new Date(Date.now() - 15 * 60000),
    booth: 'FPT Software',
  },
  {
    id: '2',
    name: 'Tran Minh Hieu',
    major: 'Computer Science',
    year: 4,
    timestamp: new Date(Date.now() - 10 * 60000),
    booth: 'Google Vietnam',
  },
  {
    id: '3',
    name: 'Le Thi Hanh',
    major: 'Business Administration',
    year: 3,
    timestamp: new Date(Date.now() - 8 * 60000),
    booth: 'Samsung Electronics',
  },
  {
    id: '4',
    name: 'Pham Van Thanh',
    major: 'Information Technology',
    year: 2,
    timestamp: new Date(Date.now() - 5 * 60000),
    booth: 'Accenture Vietnam',
  },
  {
    id: '5',
    name: 'Hoang Minh Anh',
    major: 'Telecommunications',
    year: 4,
    timestamp: new Date(Date.now() - 3 * 60000),
    booth: 'Viettel Solutions',
  },
]

export const mockPeakHours = [
  { hour: 9, count: 45 },
  { hour: 10, count: 78 },
  { hour: 11, count: 92 },
  { hour: 12, count: 65 },
  { hour: 13, count: 54 },
  { hour: 14, count: 128 },
  { hour: 15, count: 115 },
  { hour: 16, count: 98 },
  { hour: 17, count: 67 },
]

export const mockPrizes = [
  {
    id: '1',
    type: 'Early Bird',
    count: 50,
    description: 'First 50 visitors',
    prize: 'Gift set + Merchandise',
    winners: 42,
  },
  {
    id: '2',
    type: 'Lucky Draw',
    count: 20,
    description: '20+ booth visits',
    prize: 'Laptop / Tablet',
    winners: 0,
  },
  {
    id: '3',
    type: 'Booth Special',
    count: 100,
    description: 'Booth raffle',
    prize: 'Various (per booth)',
    winners: 73,
  },
]

export const mockTrends = [
  { name: 'Mon', visitors: 234, scans: 421 },
  { name: 'Tue', visitors: 321, scans: 556 },
  { name: 'Wed', visitors: 289, scans: 512 },
  { name: 'Thu', visitors: 412, scans: 678 },
  { name: 'Fri', visitors: 567, scans: 892 },
  { name: 'Sat', visitors: 678, scans: 1024 },
  { name: 'Sun', visitors: 456, scans: 789 },
]
